name: Zeebe Repo dispatch E2E tests

on:
  workflow_dispatch:
    inputs:
      generation:
        description: 'Specifies the generation template which should be used by the testbench run'
        required: false
        default: 'Zeebe SNAPSHOT'
        type: string
      branch:
        description: 'Specifies the branch, for which the QA Testbench run should be executed'
        default: 'main'
        required: false
        type: string

jobs:
  e2e:
    strategy:
      # do not cancel other jobs if one fails
      fail-fast: false
    name: Release E2E
    uses: ./.github/workflows/zeebe-e2e-testbench.yaml
    with:
      branch: ${{ inputs.branch }}
      generation: ${{ inputs.generation }}
    secrets: inherit
